//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angular02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.Vehiculo = new HashSet<Vehiculo>();
        }
    
        public long idpersona { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string tdocumento { get; set; }
        public string docmento { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
    
        public virtual ICollection<Vehiculo> Vehiculo { get; set; }
    }
}
